### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by zgbkdlm** [gabrielvc/mcg_diff#1]
Hi,

I am working on a project that needs to integrate your implementation of MCGdiff. However, your repo does not specify a license, and as such no permissions are granted. I am not even allowed to clone your repo, even though github provides the functionality. Could you please add a license? 

Thank you!

**Comment by gabrielvc** [comment]
Hi,

Thank you for pointing out, I've just added a license. 

Regards,
G

**Comment by zgbkdlm** [comment]
Lovely!
